### ISSUE TITLE
OME Metadata: TypeError: Object of type dtype[uint8] is not JSON serializable

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#1178]
Seeing an error with the OME source from `django-large-image`

```py
TypeError: Object of type dtype[uint8] is not JSON serializable
```

Reproduced here:

```py
>>> import large_image
>>> import json
>>> source = large_image.open('/data/rasters/large_image_test_files/sample.ome.tif')
>>> type(source)
<class 'large_image_source_ometiff.OMETiffFileTileSource'>
>>> json.dumps(source.getMetadata())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/local/KHQ/bane.sullivan/.pyenv/versions/3.11.0/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/KHQ/bane.sullivan/.pyenv/versions/3.11.0/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/KHQ/bane.sullivan/.pyenv/versions/3.11.0/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/local/KHQ/bane.sullivan/.pyenv/versions/3.11.0/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type dtype[uint16] is not JSON serializable
>>> 
```

**Comment by banesullivan** [comment]
Should we add a test in large-image that makes sure `json.dumps()` works for a handle of methods like `getMetadata()` `getPixel()` and `getHistogram()`

**Comment by manthey** [comment]
Hmm... `histogram` deliberately returns numpy arrays, but `getMetadata` and `getPixel` should both be serializable.

**Comment by manthey** [comment]
Fixed by stringifying dtype in metadata.  I also added a test for `getMetadata` and `getPixel`, but accidentally pushed it to master so don't have  PR to point to.  I'll close this issue.
