### ISSUE TITLE
Plugin fails to initialize when using an older memcached

### ISSUE THREAD

**Issue by jbeezley** [girder/large_image#145]
On travis with Ubuntu 14.04 with memcached 0.44, large_image fails to start with the following error:
```
ERROR: Failed to load plugin "large_image":
Traceback (most recent call last):
  File "girder/utility/plugin_utilities.py", line 87, in loadPlugins
    root, appconf, apiRoot = loadPlugin(plugin, root, appconf, apiRoot)
  File "girder/utility/plugin_utilities.py", line 212, in loadPlugin
    pluginLoadMethod(info)
  File "girder/utility/plugin_utilities.py", line 416, in wrapped
    return func(*arg, **kw)
  File "/home/travis/build/DigitalSlideArchive/digital_slide_archive/build/girder/plugins/large_image/server/base.py", line 198, in load
    from .rest import TilesItemResource, LargeImageResource, AnnotationResource
  File "/home/travis/build/DigitalSlideArchive/digital_slide_archive/build/girder/plugins/large_image/server/rest/__init__.py", line 20, in <module>
    from .tiles import TilesItemResource
  File "/home/travis/build/DigitalSlideArchive/digital_slide_archive/build/girder/plugins/large_image/server/rest/tiles.py", line 29, in <module>
    from ..models import TileGeneralException
  File "/home/travis/build/DigitalSlideArchive/digital_slide_archive/build/girder/plugins/large_image/server/models/__init__.py", line 23, in <module>
    from .image_item import ImageItem
  File "/home/travis/build/DigitalSlideArchive/digital_slide_archive/build/girder/plugins/large_image/server/models/image_item.py", line 33, in <module>
    from ..tilesource import AvailableTileSources, TileSourceException
  File "/home/travis/build/DigitalSlideArchive/digital_slide_archive/build/girder/plugins/large_image/server/tilesource/__init__.py", line 22, in <module>
    from .base import TileSource, getTileSourceFromDict, TileSourceException, \
  File "/home/travis/build/DigitalSlideArchive/digital_slide_archive/build/girder/plugins/large_image/server/tilesource/base.py", line 23, in <module>
    from ..cache_util import tileCache, tileLock, strhash, methodcache
  File "/home/travis/build/DigitalSlideArchive/digital_slide_archive/build/girder/plugins/large_image/server/cache_util/__init__.py", line 20, in <module>
    from .cache import LruCacheMetaclass, tileCache, tileLock, strhash, methodcache
  File "/home/travis/build/DigitalSlideArchive/digital_slide_archive/build/girder/plugins/large_image/server/cache_util/cache.py", line 171, in <module>
    tileCache, tileLock = CacheFactory().getCache()
  File "/home/travis/build/DigitalSlideArchive/digital_slide_archive/build/girder/plugins/large_image/server/cache_util/cachefactory.py", line 111, in getCache
    cache = MemCache(url, memcachedUsername, memcachedPassword)
  File "/home/travis/build/DigitalSlideArchive/digital_slide_archive/build/girder/plugins/large_image/server/cache_util/memcache.py", line 56, in __init__
    behaviors=behaviors)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pylibmc/client.py", line 143, in __init__
    behaviors=_behaviors_numeric(behaviors))
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pylibmc/client.py", line 112, in _behaviors_numeric
    raise ValueError("unknown behavior names: %s" % (names,))
ValueError: unknown behavior names: dead_timeout
```

Here is the memcached package information:
```
$ apt-cache show libmemcached-dev
Package: libmemcached-dev
Priority: extra
Section: libdevel
Installed-Size: 1028
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Monty Taylor <mordred@inaugust.com>
Architecture: amd64
Source: libmemcached
Version: 0.44-1.1build1
Depends: libmemcached6 (= 0.44-1.1build1), libhashkit0 (= 0.44-1.1build1), libmemcachedutil1 (= 0.44-1.1build1), libmemcachedprotocol0 (= 0.44-1.1build1)
Filename: pool/main/libm/libmemcached/libmemcached-dev_0.44-1.1build1_amd64.deb
Size: 313510
MD5sum: 173cec20017e9ee70d1b6b46493da844
SHA1: f9ef8cadc8061725c9cee3ce7dfd164fd3bc2f59
SHA256: 578e778fd93b13245be43cb869b20e2aedfc53acdd8fe231ca38ef4e69b019dd
Description: Development files for libmemcached
Homepage: http://tangent.org/552/libmemcached.html
Description-md5: ee21fa04cba54da4c95743721db9bde5
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 5y
```

**Comment by manthey** [comment]
Resolved by PR #157.
