### ISSUE TITLE
Better error type/message for non-existing files

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#656]
If you try to open a file that does not exist, `large_image` throws a vague error:

```py
ERROR 4: foo.tiff: No such file or directory
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/ct/tb7xx5mx3lncpzxd_c8tw_6h0000gn/T/ipykernel_4931/3193984606.py in <module>
----> 1 ts = large_image.open('foo.tiff')

~/Software/kw/large_image/large_image/tilesource/__init__.py in open(*args, **kwargs)
    133     :returns: A tilesource for the passed arguments.
    134     """
--> 135     return getTileSource(*args, **kwargs)
    136 
    137 

~/Software/kw/large_image/large_image/tilesource/__init__.py in getTileSource(*args, **kwargs)
    121     if not len(AvailableTileSources):
    122         loadTileSources()
--> 123     return getTileSourceFromDict(AvailableTileSources, *args, **kwargs)
    124 
    125 

~/Software/kw/large_image/large_image/tilesource/__init__.py in getTileSourceFromDict(availableSources, pathOrUri, *args, **kwargs)
    106     :returns: a tile source instance or and error.
    107     """
--> 108     sourceName = getSourceNameFromDict(availableSources, pathOrUri, *args, **kwargs)
    109     if sourceName:
    110         return availableSources[sourceName](pathOrUri, *args, **kwargs)

~/Software/kw/large_image/large_image/tilesource/__init__.py in getSourceNameFromDict(availableSources, pathOrUri, *args, **kwargs)
     73     extensions = [ext.lower() for ext in os.path.basename(uriWithoutProtocol).split('.')[1:]]
     74     properties = {
---> 75         'geospatial': isGeospatial(pathOrUri),
     76     }
     77     sourceList = []

~/Software/kw/large_image/large_image/tilesource/__init__.py in isGeospatial(path)
     29     except Exception:
     30         return False
---> 31     if ds.GetGCPs() and ds.GetGCPProjection():
     32         return True
     33     if ds.GetProjection():

AttributeError: 'NoneType' object has no attribute 'GetGCPs'
```

Looking at the stdout, it appears GDAL logged an error: `ERROR 4: foo.tiff: No such file or directory`

Perhaps this is as simple as adding the following check:

```py
if not ds:
    raise OSError(f'File not found: {path}')
```

**Comment by banesullivan** [comment]
I'd like to reopen this issue for URL files when using GDAL's VFS interface. For example:

```py
>>> import large_image
>>> # attempt opening 'https://foo.com/bar.png' over VSI
>>> large_image.open('/vsicurl?url=https%3A%2F%2Ffoo.com%2Fbar.png&use_head=no&list_dir=no')
ERROR 4: `/vsicurl?url=https%3A%2F%2Ffoo.com%2Fbar.png&use_head=no&list_dir=no' not recognized as a supported file format.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bane/anaconda3/envs/geospatial/lib/python3.8/site-packages/large_image/tilesource/__init__.py", line 140, in open
    return getTileSource(*args, **kwargs)
  File "/Users/bane/anaconda3/envs/geospatial/lib/python3.8/site-packages/large_image/tilesource/__init__.py", line 128, in getTileSource
    return getTileSourceFromDict(AvailableTileSources, *args, **kwargs)
  File "/Users/bane/anaconda3/envs/geospatial/lib/python3.8/site-packages/large_image/tilesource/__init__.py", line 113, in getTileSourceFromDict
    sourceName = getSourceNameFromDict(availableSources, pathOrUri, *args, **kwargs)
  File "/Users/bane/anaconda3/envs/geospatial/lib/python3.8/site-packages/large_image/tilesource/__init__.py", line 80, in getSourceNameFromDict
    'geospatial': isGeospatial(pathOrUri),
  File "/Users/bane/anaconda3/envs/geospatial/lib/python3.8/site-packages/large_image/tilesource/__init__.py", line 34, in isGeospatial
    if ds.GetGCPs() and ds.GetGCPProjection():
AttributeError: 'NoneType' object has no attribute 'GetGCPs'
```

**Comment by banesullivan** [comment]
Also, I just noticed this isn't working for local paths still on 1.8.11

```py
>>> import large_image
>>> large_image.__file__
'/Users/bane/anaconda3/envs/geospatial/lib/python3.8/site-packages/large_image/__init__.py'
>>> large_image.__version__
'1.8.11'
>>> large_image.open('foo.tif')
ERROR 4: foo.tif: No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bane/anaconda3/envs/geospatial/lib/python3.8/site-packages/large_image/tilesource/__init__.py", line 140, in open
    return getTileSource(*args, **kwargs)
  File "/Users/bane/anaconda3/envs/geospatial/lib/python3.8/site-packages/large_image/tilesource/__init__.py", line 128, in getTileSource
    return getTileSourceFromDict(AvailableTileSources, *args, **kwargs)
  File "/Users/bane/anaconda3/envs/geospatial/lib/python3.8/site-packages/large_image/tilesource/__init__.py", line 113, in getTileSourceFromDict
    sourceName = getSourceNameFromDict(availableSources, pathOrUri, *args, **kwargs)
  File "/Users/bane/anaconda3/envs/geospatial/lib/python3.8/site-packages/large_image/tilesource/__init__.py", line 80, in getSourceNameFromDict
    'geospatial': isGeospatial(pathOrUri),
  File "/Users/bane/anaconda3/envs/geospatial/lib/python3.8/site-packages/large_image/tilesource/__init__.py", line 34, in isGeospatial
    if ds.GetGCPs() and ds.GetGCPProjection():
AttributeError: 'NoneType' object has no attribute 'GetGCPs'
```

**Comment by banesullivan** [comment]
Ideally these should raise an `OSError` or `TileSourceFileNotFoundError`

**Comment by manthey** [comment]
Curiously, this behavior is different in the conda installation and the pip installation.
